#!/bin/bash

C=0

while read line; do
    pC="$(printf "%0*d" 3 $C)"
#    echo highlight C$pC ctermfg=$pC guifg=$line
    echo "syntax region C$pC matchgroup=EscSeq start=\"\e\[38;5;${C}m\" end=\"\e\[0m\" concealends"
    ((C++))
done < rgb_values.txt
